-- Core Lookup Values Table
-- Version: 1.0
-- Description: Centralized lookup values for LOVs and reference data

-- drop table core_lookup_values purge;

create table core_lov_currencies (
    currency_id                 number generated by default on null as identity (start with 1) primary key not null
  , currency_code               varchar2(50 char) not null
  , currency_name               varchar2(200 char) not null
  , currency_symbol             varchar2(10 char) not null
  , decimal_places              number not null
  , numeric_code                number not null
  , display_seq                 number default 0
  , active_yn                   varchar2(1 char) default 'Y' not null
  , created_by                  varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                  timestamp with local time zone default localtimestamp not null
  , last_updated_by             varchar2(60 char)
  , last_updated_on             timestamp with local time zone
  , constraint uk_core_lov_currencies_code unique (currency_code)
  , constraint chk_core_lov_currencies_active_yn check (active_yn in ('Y', 'N'))
  , constraint core_lov_currencies_ck_01 check (currency_code = upper(trim(currency_code)) and instr(currency_code, ' ') = 0)
);

-- column comments
begin
  execute immediate 'comment on column core_lov_currencies.currency_id is ''Unique identifier for the lookup value (Primary Key).''';
  execute immediate 'comment on column core_lov_currencies.currency_code is ''Category of the lookup value (e.g., PROJECT_TYPE, PROJECT_STATUS, TICKET_PRIORITY).''';
  execute immediate 'comment on column core_lov_currencies.currency_name is ''Name of the currency (e.g., US Dollar, Euro).''';
  execute immediate 'comment on column core_lov_currencies.currency_symbol is ''Symbol of the currency (e.g., $, €).''';
  execute immediate 'comment on column core_lov_currencies.decimal_places is ''Number of decimal places for the currency.''';
  execute immediate 'comment on column core_lov_currencies.numeric_code is ''Numeric code of the currency.''';
  execute immediate 'comment on column core_lov_currencies.display_seq is ''Sort order for display purposes.''';
  execute immediate 'comment on column core_lov_currencies.active_yn is ''Indicates if the currency is active (Y) or not (N).''';
  execute immediate 'comment on column core_lov_currencies.created_by is ''User who created the record.''';
  execute immediate 'comment on column core_lov_currencies.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column core_lov_currencies.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column core_lov_currencies.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table core_lov_currencies is ''Centralized lookup values for LOVs and reference data across the application.''';
end;
/

-- Create indexes

create index idx_core_lov_currencies_code on core_lov_currencies(currency_code, active_yn);
