-- Core Users Table
-- Version: 2.0
-- Description: System users with authentication and system-specific information

-- drop table core_users purge;

create table core_users (
    user_id                     number generated by default on null as identity (start with 1) primary key not null
  , entity_id                   number
  , username                    varchar2(100 char) not null
  , display_username            varchar2(100 char)
  , system_email                varchar2(100 char)
  , system_phone                varchar2(50 char)
  , timezone                    varchar2(50 char)
  , last_login                  timestamp with local time zone
  , failed_login_attempts       number default 0
  , account_locked_yn           varchar2(1 char) default 'N'
  , active_yn                   varchar2(1 char) default 'Y' not null
  , created_by                  varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                  timestamp with local time zone default localtimestamp not null
  , last_updated_by             varchar2(60 char)
  , last_updated_on             timestamp with local time zone
  --, constraint fk_core_users_entity foreign key (entity_id) references core_entities(entity_id)
  , constraint uk_core_users_username unique (username)
  , constraint uk_core_users_system_email unique (system_email)
  , constraint chk_core_users_account_locked check (account_locked_yn in ('Y', 'N'))
  , constraint chk_core_users_active_yn check (active_yn in ('Y', 'N'))
);

-- Constraint to enforce uppercase username
alter table core_users add constraint chk_core_users_username_uppercase check (upper(username) = username);

-- column comments
begin
  execute immediate 'comment on column core_users.user_id is ''Unique identifier for the user (Primary Key).''';
  execute immediate 'comment on column core_users.entity_id is ''References the entity record for this user.''';
  execute immediate 'comment on column core_users.username is ''Unique username for login.''';
  execute immediate 'comment on column core_users.display_username is ''Display name for the user.''';
  execute immediate 'comment on column core_users.system_email is ''System email address for the user.''';
  execute immediate 'comment on column core_users.system_phone is ''System phone number for the user.''';
  execute immediate 'comment on column core_users.timezone is ''User''''s timezone.''';
  execute immediate 'comment on column core_users.last_login is ''Last login timestamp.''';
  execute immediate 'comment on column core_users.failed_login_attempts is ''Number of failed login attempts.''';
  execute immediate 'comment on column core_users.account_locked_yn is ''Indicates if the account is locked (Y) or not (N).''';
  execute immediate 'comment on column core_users.active_yn is ''Indicates if the user is active (Y) or not (N).''';
  execute immediate 'comment on column core_users.created_by is ''User who created the record.''';
  execute immediate 'comment on column core_users.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column core_users.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column core_users.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table core_users is ''System users with authentication and system-specific information.''';
end;
/