-- PMS Projects Table
-- Version: 1.0
-- Description: Projects for Project Management System


create table pms_projects (
    project_id                  number generated by default on null as identity (start with 1) primary key not null
  , tenant_id                   number not null
  , project_code                varchar2(50 char) not null
  , project_prefix              varchar2(4 char)
  , project_name                varchar2(100 char) not null
  , project_description         varchar2(500 char)
  --, project_type                varchar2(50 char)
  --, project_status              varchar2(20 char)
  , start_date                  date
  , end_date                    date
  , budget                      number
  , currency_id                 number
  , project_manager_id          number
  , project_lead_id             number
  , project_url                 varchar2(500 char)
  , repository_url              varchar2(500 char)
  , active_yn                   varchar2(1 char) default 'Y' not null
  , created_by                  varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                  timestamp with local time zone default localtimestamp not null
  , last_updated_by             varchar2(60 char)
  , last_updated_on             timestamp with local time zone
  , constraint fk_pms_projects_manager foreign key (project_manager_id) references core_users(user_id)
  , constraint fk_pms_projects_lead foreign key (project_lead_id) references core_users(user_id)
  , constraint uk_pms_projects_tenant_code unique (tenant_id, project_code)
  , constraint chk_pms_projects_active_yn check (active_yn in ('Y', 'N'))
  , constraint pms_projects_ck_01 check (project_code = upper(trim(project_code)) and instr(project_code, ' ') = 0)
);

-- Performance indexes

-- column comments
begin
  execute immediate 'comment on column pms_projects.project_id is ''Unique identifier for the project (Primary Key).''';
  execute immediate 'comment on column pms_projects.project_code is ''Unique code for the project, e.g., PROJ-001.''';
  execute immediate 'comment on column pms_projects.project_name is ''Name of the project.''';
  execute immediate 'comment on column pms_projects.project_description is ''Description of the project.''';
  --execute immediate 'comment on column pms_projects.project_type is ''Type of project, e.g., DEVELOPMENT, MAINTENANCE, RESEARCH.''';
  --execute immediate 'comment on column pms_projects.project_status is ''Status of the project, e.g., ACTIVE, ON_HOLD, COMPLETED.''';
  execute immediate 'comment on column pms_projects.start_date is ''Start date of the project.''';
  execute immediate 'comment on column pms_projects.end_date is ''End date of the project.''';
  execute immediate 'comment on column pms_projects.budget is ''Budget allocated for the project.''';
  execute immediate 'comment on column pms_projects.currency is ''Currency for the budget, e.g., USD, EUR.''';
  execute immediate 'comment on column pms_projects.project_manager_id is ''User who manages the project.''';
  execute immediate 'comment on column pms_projects.project_lead_id is ''User who leads the project.''';
  execute immediate 'comment on column pms_projects.project_url is ''URL to the project documentation.''';
  execute immediate 'comment on column pms_projects.repository_url is ''URL to the project repository.''';
  execute immediate 'comment on column pms_projects.active_yn is ''Indicates if the project is active (Y) or not (N).''';
  execute immediate 'comment on column pms_projects.created_by is ''User who created the record.''';
  execute immediate 'comment on column pms_projects.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column pms_projects.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column pms_projects.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table pms_projects is ''Projects for Project Management System.''';
end;
/