-- PMS Sprints Table
-- Version: 1.0
-- Description: Project sprints



create table pms_sprints (
    sprint_id                   number generated by default on null as identity (start with 1) primary key not null
  , project_id                  number not null
  , sprint_name                 varchar2(100 char) not null
  , sprint_description          varchar2(500 char)
  , start_on                    date not null
  , end_on                      date not null
  , active_yn                   varchar2(1 char) default 'Y' not null
  , created_by                  varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                  timestamp with local time zone default localtimestamp not null
  , last_updated_by             varchar2(60 char)
  , last_updated_on             timestamp with local time zone
  , constraint fk_pms_sprints_project foreign key (project_id) references pms_projects(project_id)
  , constraint chk_pms_sprints_active_yn check (active_yn in ('Y', 'N'))
);

-- Performance indexes
create index idx_pms_sprints_project on pms_sprints(project_id);

-- column comments
begin
  execute immediate 'comment on column pms_sprints.sprint_id is ''Unique identifier for the sprint (Primary Key).''';
  execute immediate 'comment on column pms_sprints.project_id is ''References the project for this sprint.''';
  execute immediate 'comment on column pms_sprints.sprint_name is ''Name of the sprint.''';
  execute immediate 'comment on column pms_sprints.sprint_description is ''Description of the sprint.''';
  execute immediate 'comment on column pms_sprints.start_on is ''Start date of the sprint.''';
  execute immediate 'comment on column pms_sprints.end_on is ''End date of the sprint.''';
  execute immediate 'comment on column pms_sprints.active_yn is ''Indicates if the sprint is active (Y) or not (N).''';
  execute immediate 'comment on column pms_sprints.created_by is ''User who created the record.''';
  execute immediate 'comment on column pms_sprints.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column pms_sprints.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column pms_sprints.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table pms_sprints is ''Project sprints with planning and tracking information.''';
end;
/