-- TaskFlow Board Columns Table
-- Version: 1.0
-- Description: Columns for Kanban boards



create table tf_board_columns (
    board_column_id             number generated by default on null as identity (start with 1) primary key not null
  , board_id                    number not null
  , column_name                 varchar2(100 char) not null
  , display_seq                 number default 0 not null
  , hex_color                 varchar2(100 char)
  , class_icon                  varchar2(100 char)
  , description                 varchar2(500 char)
  , active_yn                   varchar2(1 char) default 'Y' not null
  , created_by                  varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                  timestamp with local time zone default localtimestamp not null
  , last_updated_by             varchar2(60 char)
  , last_updated_on             timestamp with local time zone
  , constraint fk_board_columns_board foreign key (board_id) references tf_boards(board_id)
  , constraint uk_board_columns_order unique (board_id, display_seq)
  , constraint chk_board_columns_active_yn check (active_yn in ('Y', 'N'))
);

-- Performance indexes
create index idx_tf_board_columns_board on tf_board_columns(board_id);

-- column comments
begin
  execute immediate 'comment on column tf_board_columns.board_column_id is ''Unique identifier for the board column (Primary Key).''';
  execute immediate 'comment on column tf_board_columns.board_id is ''References the board for this column.''';
  execute immediate 'comment on column tf_board_columns.column_name is ''Name of the column.''';
  execute immediate 'comment on column tf_board_columns.display_seq is ''Order of the column within the board.''';
  execute immediate 'comment on column tf_board_columns.hex_color is ''CSS class name that represents the color for this column.''';
  execute immediate 'comment on column tf_board_columns.class_icon is ''CSS class name that represents the icon for this column.''';
  execute immediate 'comment on column tf_board_columns.description is ''Description of the column.''';
  execute immediate 'comment on column tf_board_columns.active_yn is ''Indicates if the column is active (Y) or not (N).''';
  execute immediate 'comment on column tf_board_columns.created_by is ''User who created the record.''';
  execute immediate 'comment on column tf_board_columns.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column tf_board_columns.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column tf_board_columns.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table tf_board_columns is ''Columns for Kanban boards with ordering and WIP limits.''';
end;
/