-- TaskFlow Boards Table
-- Version: 1.0
-- Description: Kanban boards for TaskFlow system

-- drop table tf_boards purge;

--alter table tf_boards modify default_flag varchar2(1 char) null;

-- Example of boards
/*
TENANT (1)
├── PROYECTO A (1)
│   ├── Sprint 1
│   │   └── Board: "Sprint 1 Board"
│   ├── Sprint 2
│   │   └── Board: "Sprint 2 Board"
│   └── Board: "Proyecto A General Board"
├── PROYECTO B (1)
│   ├── Sprint 1
│   │   └── Board: "Sprint 1 Board"
│   └── Board: "Proyecto B General Board"
└── Board: "Tenant General Board"
*/



create table tf_boards (
    board_id                    number generated by default on null as identity (start with 1) primary key not null
  , sprint_id                   number
  , board_name                  varchar2(100 char) not null
  , board_code                  varchar2(50 char) not null
  , description                 varchar2(500 char)
  , workflow_template_id        number -- Optional reference to workflow template
  , default_yn                  varchar2(1 char) default 'N' not null
  , active_yn                   varchar2(1 char) default 'Y' not null
  , created_by                  varchar2(60 char) default 
                                  coalesce(
                                    sys_context('apex$session','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                  timestamp with local time zone default localtimestamp not null
  , last_updated_by             varchar2(60 char)
  , last_updated_on             timestamp with local time zone
  , constraint uk_boards_code unique (board_code)
  , constraint chk_boards_default check (default_yn in ('Y', 'N'))
  , constraint chk_boards_active_yn check (active_yn in ('Y', 'N'))
);

-- Performance indexes


alter table tf_boards add constraint fk_boards_sprint foreign key (sprint_id) references pms_sprints(sprint_id);
alter table tf_boards add constraint fk_boards_workflow_template foreign key (workflow_template_id) references tf_workflow_templates(workflow_template_id);


-- column comments
begin
  execute immediate 'comment on column tf_boards.board_id is ''Unique identifier for the board (Primary Key).''';
  execute immediate 'comment on column tf_boards.sprint_id is ''References the sprint associated with this board.''';
  execute immediate 'comment on column tf_boards.board_name is ''Display name for the board.''';
  execute immediate 'comment on column tf_boards.board_code is ''Unique code for the board.''';
  execute immediate 'comment on column tf_boards.description is ''Description of the board.''';
  execute immediate 'comment on column tf_boards.workflow_template_id is ''References a workflow template for predesigned columns (optional).''';
  execute immediate 'comment on column tf_boards.default_yn is ''Indicates if this is the default board for the sprint, can be Y or N.''';
  execute immediate 'comment on column tf_boards.active_yn is ''Indicates if the board is active (Y) or not (N).''';
  execute immediate 'comment on column tf_boards.created_by is ''User who created the record.''';
  execute immediate 'comment on column tf_boards.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column tf_boards.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column tf_boards.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table tf_boards is ''Kanban boards for TaskFlow system, supporting custom columns and optional workflow templates.''';
end;
/