-- TaskFlow Ticket Priorities Table
-- Version: 1.0
-- Description: Lookup table for ticket priorities with visual styles
-- Example priorities:
--   LOW       - class color: tf-priority-low-color, class icon: tf-icon-low
--   MEDIUM    - class color: tf-priority-medium-color, class icon: tf-icon-medium
--   HIGH      - class color: tf-priority-high-color, class icon: tf-icon-high
--   CRITICAL  - class color: tf-priority-critical-color, class icon: tf-icon-critical

create table tf_ticket_priorities (
    ticket_priority_id          number generated by default on null as identity (start with 1) primary key not null
  , priority_name               varchar2(100 char) not null
  , priority_code               varchar2(50 char) not null
  , description                 varchar2(500 char)
  , class_color                 varchar2(100 char)
  , class_icon                  varchar2(100 char)
  , display_seq                 number default 0 not null
  , default_yn                  varchar2(1 char) default 'N' not null
  , active_yn                   varchar2(1 char) default 'Y' not null
  , created_by                  varchar2(60 char) default
                                  coalesce(
                                    sys_context('apex$session','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                  timestamp with local time zone default localtimestamp not null
  , last_updated_by             varchar2(60 char)
  , last_updated_on             timestamp with local time zone
  , constraint uk_ticket_priorities_code unique (priority_code)
  , constraint uk_ticket_priorities_name unique (priority_name)
  , constraint chk_ticket_priorities_default check (default_yn in ('Y', 'N'))
  , constraint chk_ticket_priorities_active_yn check (active_yn in ('Y', 'N'))
);

-- column comments
begin
  execute immediate 'comment on column tf_ticket_priorities.ticket_priority_id is ''Unique identifier for the ticket priority (Primary Key).''';
  execute immediate 'comment on column tf_ticket_priorities.priority_name is ''Display name for the ticket priority.''';
  execute immediate 'comment on column tf_ticket_priorities.priority_code is ''Unique code for the ticket priority.''';
  execute immediate 'comment on column tf_ticket_priorities.description is ''Description of the ticket priority.''';
  execute immediate 'comment on column tf_ticket_priorities.class_color is ''CSS class name that represents the color for this priority.''';
  execute immediate 'comment on column tf_ticket_priorities.class_icon is ''CSS class name that represents the icon for this priority.''';
  execute immediate 'comment on column tf_ticket_priorities.display_seq is ''Determines the display order for priorities.''';
  execute immediate 'comment on column tf_ticket_priorities.default_yn is ''Indicates if this is the default priority.''';
  execute immediate 'comment on column tf_ticket_priorities.active_yn is ''Indicates if the ticket priority is active (Y) or not (N).''';
  execute immediate 'comment on column tf_ticket_priorities.created_by is ''User who created the record.''';
  execute immediate 'comment on column tf_ticket_priorities.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column tf_ticket_priorities.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column tf_ticket_priorities.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table tf_ticket_priorities is ''Lookup table defining ticket priorities with associated styling metadata.''';
end;
/

