-- TaskFlow Tickets Table
-- Version: 1.0
-- Description: Main tickets table for TaskFlow system

alter table tf_tickets rename column assignee_id to assigned_to_id;

create table tf_tickets (
    ticket_id                   number generated by default on null as identity (start with 1) primary key not null
  , board_id                    number not null
  , board_column_id             number not null
  , ticket_type_id              number not null
  , project_id                  number not null
  , sprint_id                   number
  , ticket_number               varchar2(50 char) not null
  , title                       varchar2(200 char) not null
  , description                 clob
  , acceptance_criteria         clob
  , implementation_notes        clob
  , priority_id                 number not null
  , assigned_to_id              number
  , reporter_id                 number
  , estimated_hours             number
  , actual_hours                number
  , start_on                    date
  , due_on                      date
  , end_on                      date
  , tags                        varchar2(1000 char)
  , active_yn                   varchar2(1 char) default 'Y' not null
  , created_by                  varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                  timestamp with local time zone default localtimestamp not null
  , last_updated_by             varchar2(60 char)
  , last_updated_on             timestamp with local time zone
  , constraint fk_tickets_board foreign key (board_id) references tf_boards(board_id)
  , constraint fk_tickets_board_column foreign key (board_column_id) references tf_board_columns(board_column_id)
  , constraint fk_tickets_type foreign key (ticket_type_id) references tf_ticket_types(ticket_type_id)
  , constraint fk_tickets_project foreign key (project_id) references pms_projects(project_id)
  , constraint fk_tickets_sprint foreign key (sprint_id) references pms_sprints(sprint_id)
  , constraint fk_tickets_assignee foreign key (assigned_to_id) references core_users(user_id)
  , constraint fk_tickets_reporter foreign key (reporter_id) references core_users(user_id)
  , constraint fk_tickets_priority foreign key (priority_id) references tf_ticket_priorities(ticket_priority_id)
  , constraint uk_tickets_number unique (ticket_number)
  , constraint chk_tickets_active_yn check (active_yn in ('Y', 'N'))
);

-- Performance indexes
create index idx_tf_tickets_board on tf_tickets(board_id);
create index idx_tf_tickets_board_column on tf_tickets(board_column_id);
create index idx_tf_tickets_ticket_type on tf_tickets(ticket_type_id);
create index idx_tf_tickets_project on tf_tickets(project_id);
create index idx_tf_tickets_sprint on tf_tickets(sprint_id);
create index idx_tf_tickets_assignee on tf_tickets(assigned_to_id);
create index idx_tf_tickets_reporter on tf_tickets(reporter_id);
create index idx_tf_tickets_priority on tf_tickets(priority_id);


-- column comments
begin
  execute immediate 'comment on column tf_tickets.ticket_id is ''Unique identifier for the ticket (Primary Key).''';
  execute immediate 'comment on column tf_tickets.board_id is ''References the board for this ticket.''';
  execute immediate 'comment on column tf_tickets.board_column_id is ''References the board column for this ticket.''';
  execute immediate 'comment on column tf_tickets.ticket_type_id is ''References the ticket type.''';
  execute immediate 'comment on column tf_tickets.project_id is ''References the project for this ticket.''';
  execute immediate 'comment on column tf_tickets.sprint_id is ''References the sprint for this ticket.''';
  execute immediate 'comment on column tf_tickets.ticket_number is ''Unique ticket number.''';
  execute immediate 'comment on column tf_tickets.title is ''Title of the ticket.''';
  execute immediate 'comment on column tf_tickets.description is ''Description of the ticket.''';
  execute immediate 'comment on column tf_tickets.acceptance_criteria is ''Acceptance criteria for the ticket.''';
  execute immediate 'comment on column tf_tickets.implementation_notes is ''Implementation notes for the ticket.''';
  execute immediate 'comment on column tf_tickets.priority_id is ''References the ticket priority.''';
  execute immediate 'comment on column tf_tickets.assigned_to_id is ''User assigned to the ticket.''';
  execute immediate 'comment on column tf_tickets.reporter_id is ''User who reported the ticket.''';
  execute immediate 'comment on column tf_tickets.estimated_hours is ''Estimated hours for the ticket.''';
  execute immediate 'comment on column tf_tickets.actual_hours is ''Actual hours spent on the ticket.''';
  execute immediate 'comment on column tf_tickets.start_on is ''Start date for the ticket.''';
  execute immediate 'comment on column tf_tickets.due_on is ''Due date for the ticket.''';
  execute immediate 'comment on column tf_tickets.end_on is ''Completion date for the ticket.''';
  execute immediate 'comment on column tf_tickets.tags is ''Tags for the ticket.''';
  execute immediate 'comment on column tf_tickets.active_yn is ''Indicates if the ticket is active (Y) or not (N).''';
  execute immediate 'comment on column tf_tickets.created_by is ''User who created the record.''';
  execute immediate 'comment on column tf_tickets.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column tf_tickets.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column tf_tickets.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table tf_tickets is ''Main tickets table for TaskFlow system with comprehensive tracking.''';
end;
/