-- TaskFlow Ticket Attachments Table
-- Version: 1.0
-- Description: File attachments for tickets

create table tf_ticket_attachments (
    ticket_attachment_id        number generated by default on null as identity (start with 1) primary key not null
  , ticket_id                   number not null
  , user_id                     number not null
  , file_name                   varchar2(255 char) not null
  , file_path                   varchar2(1000 char) not null
  , file_size                   number not null
  , file_mime_type              varchar2(100 char)
  , file_hash                   varchar2(64 char)
  , file_content                blob
  , description                 varchar2(500 char)
  , active_yn                   varchar2(1 char) default 'Y' not null
  , created_by                  varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                  timestamp with local time zone default localtimestamp not null
  , last_updated_by             varchar2(60 char)
  , last_updated_on             timestamp with local time zone
  , constraint fk_ticket_attachments_ticket foreign key (ticket_id) references tf_tickets(ticket_id)
  , constraint fk_ticket_attachments_user foreign key (user_id) references core_users(user_id)
  , constraint chk_ticket_attachments_active_yn check (active_yn in ('Y', 'N'))
);

-- Performance indexes
create index idx_tf_ticket_attachments_ticket on tf_ticket_attachments(ticket_id);

-- column comments
begin
  execute immediate 'comment on column tf_ticket_attachments.ticket_attachment_id is ''Unique identifier for the ticket attachment (Primary Key).''';
  execute immediate 'comment on column tf_ticket_attachments.ticket_id is ''References the ticket for this attachment.''';
  execute immediate 'comment on column tf_ticket_attachments.user_id is ''References the user who uploaded the attachment.''';
  execute immediate 'comment on column tf_ticket_attachments.file_name is ''Original name of the uploaded file.''';
  execute immediate 'comment on column tf_ticket_attachments.file_path is ''Path to the stored file.''';
  execute immediate 'comment on column tf_ticket_attachments.file_size is ''Size of the file in bytes.''';
  execute immediate 'comment on column tf_ticket_attachments.file_mime_type is ''MIME type of the file.''';
  execute immediate 'comment on column tf_ticket_attachments.file_hash is ''Hash of the file for integrity checking.''';
  execute immediate 'comment on column tf_ticket_attachments.description is ''Description of the attachment.''';
  execute immediate 'comment on column tf_ticket_attachments.active_yn is ''Indicates if the attachment is active (Y) or not (N).''';
  execute immediate 'comment on column tf_ticket_attachments.created_by is ''User who created the record.''';
  execute immediate 'comment on column tf_ticket_attachments.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column tf_ticket_attachments.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column tf_ticket_attachments.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table tf_ticket_attachments is ''File attachments for tickets with metadata and access control.''';
end;
/