-- TaskFlow Ticket Types Table
-- Version: 1.0
-- Description: Ticket types for TaskFlow system

-- Example: of ticket types
-- BUG
-- FEATURE
-- TASK
-- DOCUMENTATION
-- ENHANCEMENT

create table tf_ticket_types (
    ticket_type_id              number generated by default on null as identity (start with 1) primary key not null
  , ticket_type_name            varchar2(100 char) not null
  , ticket_type_code            varchar2(50 char) not null
  , description                 varchar2(500 char)
  , class_color                 varchar2(100 char)
  , class_icon                  varchar2(100 char)
  , display_seq                 number default 0 not null
  , default_yn                  varchar2(1 char) default 'N' not null
  , active_yn                   varchar2(1 char) default 'Y' not null
  , created_by                  varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                  timestamp with local time zone default localtimestamp not null
  , last_updated_by             varchar2(60 char)
  , last_updated_on             timestamp with local time zone
  , constraint uk_ticket_types_code unique (ticket_type_code)
  , constraint chk_ticket_types_default check (default_yn in ('Y', 'N'))
  , constraint chk_ticket_types_active_yn check (active_yn in ('Y', 'N'))
);

-- Performance indexes

-- column comments
begin
  execute immediate 'comment on column tf_ticket_types.ticket_type_id is ''Unique identifier for the ticket type (Primary Key).''';
  execute immediate 'comment on column tf_ticket_types.ticket_type_name is ''Display name for the ticket type.''';
  execute immediate 'comment on column tf_ticket_types.ticket_type_code is ''Unique code for the ticket type.''';
  execute immediate 'comment on column tf_ticket_types.description is ''Description of the ticket type.''';
  execute immediate 'comment on column tf_ticket_types.default_yn is ''Indicates if this is the default ticket type.''';
  execute immediate 'comment on column tf_ticket_types.active_yn is ''Indicates if the ticket type is active (Y) or not (N).''';
  execute immediate 'comment on column tf_ticket_types.created_by is ''User who created the record.''';
  execute immediate 'comment on column tf_ticket_types.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column tf_ticket_types.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column tf_ticket_types.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table tf_ticket_types is ''Ticket types for TaskFlow system with visual customization.''';
end;
/