-- TaskFlow Ticket Comments Table
-- Version: 1.0
-- Description: Comments for tickets


create table tf_ticket_comments (
    ticket_comment_id           number generated by default on null as identity (start with 1) primary key not null
  , ticket_id                   number not null
  , user_id                     number not null
  , comment_text                clob not null
  , is_internal                 varchar2(1 char) default 'N' not null
  , parent_comment_id           number
  , active_yn                   varchar2(1 char) default 'Y' not null
  , created_by                  varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                  timestamp with local time zone default localtimestamp not null
  , last_updated_by             varchar2(60 char)
  , last_updated_on             timestamp with local time zone
  , constraint fk_ticket_comments_ticket foreign key (ticket_id) references tf_tickets(ticket_id)
  , constraint fk_ticket_comments_user foreign key (user_id) references core_users(user_id)
  , constraint fk_ticket_comments_parent foreign key (parent_comment_id) references tf_ticket_comments(ticket_comment_id)
  , constraint chk_ticket_comments_internal check (is_internal in ('Y', 'N'))
  , constraint chk_ticket_comments_active_yn check (active_yn in ('Y', 'N'))
);

-- Performance indexes
create index idx_tf_ticket_comments_ticket on tf_ticket_comments(ticket_id);

-- column comments
begin
  execute immediate 'comment on column tf_ticket_comments.ticket_comment_id is ''Unique identifier for the ticket comment (Primary Key).''';
  execute immediate 'comment on column tf_ticket_comments.ticket_id is ''References the ticket for this comment.''';
  execute immediate 'comment on column tf_ticket_comments.user_id is ''References the user who made the comment.''';
  execute immediate 'comment on column tf_ticket_comments.comment_text is ''Text content of the comment.''';
  execute immediate 'comment on column tf_ticket_comments.is_internal is ''Indicates if this is an internal comment.''';
  execute immediate 'comment on column tf_ticket_comments.parent_comment_id is ''References the parent comment for replies.''';
  execute immediate 'comment on column tf_ticket_comments.active_yn is ''Indicates if the comment is active (Y) or not (N).''';
  execute immediate 'comment on column tf_ticket_comments.created_by is ''User who created the record.''';
  execute immediate 'comment on column tf_ticket_comments.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column tf_ticket_comments.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column tf_ticket_comments.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table tf_ticket_comments is ''Comments for tickets with support for threaded discussions.''';
end;
/