-- TaskFlow Ticket History Table
-- Version: 1.0
-- Description: History tracking for ticket changes

-- drop table tf_ticket_history purge;

create table tf_ticket_history (
    ticket_history_id           number generated by default on null as identity (start with 1) primary key not null
  , ticket_id                   number not null
  , user_id                     number
  , change_type                 varchar2(50 char) not null
  , field_name                  varchar2(100 char)
  , old_value                   varchar2(4000 char)
  , new_value                   varchar2(4000 char)
  , change_description          varchar2(1000 char)
  , change_date                 timestamp with local time zone default localtimestamp not null
  , created_by                  varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                  timestamp with local time zone default localtimestamp not null
  , last_updated_by             varchar2(60 char)
  , last_updated_on             timestamp with local time zone
  , constraint fk_ticket_history_ticket foreign key (ticket_id) references tf_tickets(ticket_id)
  , constraint fk_ticket_history_user foreign key (user_id) references core_users(user_id)
  , constraint chk_ticket_history_type check (change_type in ('CREATE', 'UPDATE', 'DELETE', 'STATUS_CHANGE', 'ASSIGNMENT', 'COMMENT'))
);

-- Performance indexes
create index idx_tf_ticket_history_ticket on tf_ticket_history(ticket_id);

-- column comments
begin
  execute immediate 'comment on column tf_ticket_history.ticket_history_id is ''Unique identifier for the ticket history entry (Primary Key).''';
  execute immediate 'comment on column tf_ticket_history.ticket_id is ''References the ticket for this history entry.''';
  execute immediate 'comment on column tf_ticket_history.user_id is ''References the user who made the change.''';
  execute immediate 'comment on column tf_ticket_history.change_type is ''Type of change made to the ticket.''';
  execute immediate 'comment on column tf_ticket_history.field_name is ''Name of the field that was changed.''';
  execute immediate 'comment on column tf_ticket_history.old_value is ''Previous value before the change.''';
  execute immediate 'comment on column tf_ticket_history.new_value is ''New value after the change.''';
  execute immediate 'comment on column tf_ticket_history.change_description is ''Description of the change made.''';
  execute immediate 'comment on column tf_ticket_history.change_date is ''Date and time when the change occurred.''';
  execute immediate 'comment on column tf_ticket_history.created_by is ''User who created the record.''';
  execute immediate 'comment on column tf_ticket_history.created_on is ''Timestamp when the record was created.''';

  -- table comment
  execute immediate 'comment on table tf_ticket_history is ''History tracking for ticket changes with detailed audit trail.''';
end;
/