-- TaskFlow Workflow Transitions Table
-- Version: 1.0
-- Description: Valid transitions between workflow template columns

create table tf_workflow_transitions (
    transition_id                 number generated by default on null as identity (start with 1) primary key not null
  , workflow_template_id         number not null
  , from_column_seq              number not null
  , to_column_seq                number not null
  , transition_name              varchar2(100 char)
  , required_fields              varchar2(1000 char)
  , auto_assign_role             varchar2(50 char)
  , validation_rule              varchar2(500 char)
  , active_yn                    varchar2(1 char) default 'Y' not null
  , created_by                   varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                   timestamp with local time zone default localtimestamp not null
  , last_updated_by              varchar2(60 char)
  , last_updated_on              timestamp with local time zone
  , constraint fk_transitions_template foreign key (workflow_template_id) references tf_workflow_templates(workflow_template_id)
  , constraint uk_transitions_unique unique (workflow_template_id, from_column_seq, to_column_seq)
  , constraint chk_transitions_active_yn check (active_yn in ('Y', 'N'))
);

-- Performance indexes
create index idx_tf_transitions_template on tf_workflow_transitions(workflow_template_id);
create index idx_tf_transitions_from on tf_workflow_transitions(workflow_template_id, from_column_seq);

-- column comments
begin
  execute immediate 'comment on column tf_workflow_transitions.transition_id is ''Unique identifier for the transition (Primary Key).''';
  execute immediate 'comment on column tf_workflow_transitions.workflow_template_id is ''References the workflow template for this transition.''';
  execute immediate 'comment on column tf_workflow_transitions.from_column_seq is ''Display sequence of the source column.''';
  execute immediate 'comment on column tf_workflow_transitions.to_column_seq is ''Display sequence of the target column.''';
  execute immediate 'comment on column tf_workflow_transitions.transition_name is ''Name of the transition, e.g., Start Work, Complete Review.''';
  execute immediate 'comment on column tf_workflow_transitions.required_fields is ''Comma-separated list of required fields for this transition, e.g., ASSIGNEE_ID,DUE_ON.''';
  execute immediate 'comment on column tf_workflow_transitions.auto_assign_role is ''Role to auto-assign when transitioning to this column, e.g., QA, DEVELOPER.''';
  execute immediate 'comment on column tf_workflow_transitions.validation_rule is ''Custom validation rule expression for this transition.''';
  execute immediate 'comment on column tf_workflow_transitions.active_yn is ''Indicates if the transition is active (Y) or not (N).''';
  execute immediate 'comment on column tf_workflow_transitions.created_by is ''User who created the record.''';
  execute immediate 'comment on column tf_workflow_transitions.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column tf_workflow_transitions.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column tf_workflow_transitions.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table tf_workflow_transitions is ''Valid transitions between workflow template columns, defining allowed moves and validation rules.''';
end;
/

