-- TaskFlow Workflow Template Columns Table
-- Version: 1.0
-- Description: Column definitions for workflow templates
-- drop table tf_workflow_template_columns purge;
create table tf_workflow_template_columns (
    template_column_id           number generated by default on null as identity (start with 1) primary key not null
  , workflow_template_id         number not null
  , column_name                  varchar2(100 char) not null
  , column_code                  varchar2(100 char) not null
  , display_seq                  number default 0 not null
  , hex_color                    varchar2(100 char)
  , class_icon                   varchar2(100 char)
  , description                  varchar2(500 char)
  , active_yn                    varchar2(1 char) default 'Y' not null
  , created_by                   varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                   timestamp with local time zone default localtimestamp not null
  , last_updated_by              varchar2(60 char)
  , last_updated_on              timestamp with local time zone
  , constraint fk_template_columns_template foreign key (workflow_template_id) references tf_workflow_templates(workflow_template_id)
  , constraint uk_template_columns_order unique (workflow_template_id, display_seq)
  , constraint chk_template_columns_active_yn check (active_yn in ('Y', 'N'))
  , constraint tf_workflow_template_columns_ck_01 check (column_code = upper(trim(column_code)) and instr(column_code, ' ') = 0)
);

-- Performance indexes
create index idx_tf_template_columns_template on tf_workflow_template_columns(workflow_template_id);

-- column comments
begin
  execute immediate 'comment on column tf_workflow_template_columns.template_column_id is ''Unique identifier for the template column (Primary Key).''';
  execute immediate 'comment on column tf_workflow_template_columns.workflow_template_id is ''References the workflow template for this column.''';
  execute immediate 'comment on column tf_workflow_template_columns.column_name is ''Name of the column, e.g., To Do, In Progress, Done.''';
  execute immediate 'comment on column tf_workflow_template_columns.column_code is ''Code of the column, e.g., TODO, IN_PROGRESS, DONE.''';
  execute immediate 'comment on column tf_workflow_template_columns.display_seq is ''Order of the column within the template.''';
  execute immediate 'comment on column tf_workflow_template_columns.hex_color is ''Hexadecimal color code for this column (e.g., #0073E6, #28A745).''';
  execute immediate 'comment on column tf_workflow_template_columns.class_icon is ''CSS class name that represents the default icon for this column.''';
  execute immediate 'comment on column tf_workflow_template_columns.description is ''Description of the column and its purpose.''';
  execute immediate 'comment on column tf_workflow_template_columns.active_yn is ''Indicates if the column is active (Y) or not (N).''';
  execute immediate 'comment on column tf_workflow_template_columns.created_by is ''User who created the record.''';
  execute immediate 'comment on column tf_workflow_template_columns.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column tf_workflow_template_columns.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column tf_workflow_template_columns.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table tf_workflow_template_columns is ''Column definitions for workflow templates, defining the structure and default properties of board columns.''';
end;
/

