-- TaskFlow Workflow Templates Table
-- Version: 1.0
-- Description: Reusable workflow templates for boards

create table tf_workflow_templates (
    workflow_template_id         number generated by default on null as identity (start with 1) primary key not null
  , template_name                varchar2(100 char) not null
  , template_code                varchar2(50 char) not null
  , active_yn                    varchar2(1 char) default 'Y' not null
  , created_by                   varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                   timestamp with local time zone default localtimestamp not null
  , last_updated_by              varchar2(60 char)
  , last_updated_on              timestamp with local time zone
  , constraint uk_workflow_templates_code unique (template_code)
  , constraint chk_workflow_templates_active_yn check (active_yn in ('Y', 'N'))
);

-- Performance indexes
create index idx_tf_workflow_templates_active on tf_workflow_templates(active_yn);

-- column comments
begin
  execute immediate 'comment on column tf_workflow_templates.workflow_template_id is ''Unique identifier for the workflow template (Primary Key).''';
  execute immediate 'comment on column tf_workflow_templates.template_name is ''Display name for the workflow template.''';
  execute immediate 'comment on column tf_workflow_templates.template_code is ''Unique code for the workflow template.''';
  execute immediate 'comment on column tf_workflow_templates.active_yn is ''Indicates if the template is active (Y) or not (N).''';
  execute immediate 'comment on column tf_workflow_templates.created_by is ''User who created the record.''';
  execute immediate 'comment on column tf_workflow_templates.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column tf_workflow_templates.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column tf_workflow_templates.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table tf_workflow_templates is ''Reusable workflow templates for boards, defining standard column structures and processes.''';
end;
/

